config/routes.rb
Rails.application.routes.draw do

  resources :walls

  get 'pages/about'
  get 'pages/home'
  get 'pages/resources'
  get 'pages/samplewall'

  
  resources :wall_memberships, only: [:create, :destroy]
  
  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    authenticated :user do
      root to: "pages#home", as: :authenticated_root, via: :get
    end
    
    unauthenticated do
      root to: "devise/sessions#new"
    end
  end

  resources :users

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin
    has_attribute?(:admin)
    return email == 'cmidenyo@outlook.com'
  end

  has_many :wall_memberships
  has_many :walls, through: :wall_memberships
  
  def member?(wall)
    self.walls.include?(wall)
  end

  def to_s
    email
  end

end

app/models/wall.rb
class Wall < ActiveRecord::Base
    has_many :wall_memberships
    has_many :users, through: :wall_memberships
end

app/models/wall_membership.rb
class WallMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :wall
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :email, :username, :birthday])
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :email, :username, :birthday])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def resources
  end
  
  def samplewall
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    :walls
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/controllers/wall_memberships_controller.rb
class WallMembershipsController < ApplicationController
  def create
    wall = Wall.find(params[:wall_id])
    current_user.walls << wall
    redirect_to wall
  end

  def destroy
    membership = Wall_Membership.find(params[:id])
    wall = membership.wall
    membership.destroy
    redirect_to wall

  end
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  require "pathname"
  before_action :set_wall, only: [:show, :edit, :update, :destroy]

  # GET /walls
  # GET /walls.json
  def index
    @walls = Wall.all
    @user_walls = current_user.walls
  end

  # GET /walls/1
  # GET /walls/1.json
  def show
    @forum = "/forum/#{@wall.title.downcase}"
  end

  # GET /walls/new
  def newgit
    @wall = Wall.new
  end

  # GET /walls/1/edit
  def edit
  end

  # POST /walls
  # POST /walls.json
  def create
    @wall = Wall.new(wall_params)

    respond_to do |format|
      if @wall.save
        format.html { redirect_to @wall, notice: 'Wall was successfully created.' }
        format.json { render :show, status: :created, location: @wall }
      else
        format.html { render :new }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walls/1
  # PATCH/PUT /walls/1.json
  def update
    respond_to do |format|
      if @wall.update(wall_params)
        format.html { redirect_to @wall, notice: 'Wall was successfully updated.' }
        format.json { render :show, status: :ok, location: @wall }
      else
        format.html { render :edit }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walls/1
  # DELETE /walls/1.json
  def destroy
    @wall.destroy
    respond_to do |format|
      format.html { redirect_to walls_url, notice: 'Wall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall
      @wall = Wall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_params
      params.require(:wall).permit(:title, :description)
    end
    
      
      
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wall_memberships_helper.rb
module WallMembershipsHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Walls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>

<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">WALLS</a>
                
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Sign Up', new_user_registration_path =%> 
                    </li>
                    <li>
                        <%= link_to 'Log In', new_user_session_path =%>
                    </li>
                    <li>
                        <%= link_to 'About Us', pages_about_path =%>
                    </li>
                    <li>
                        <%= link_to 'Resources', pages_resources_path =%>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<body>
  
  

        


<%= yield %>

</body>
<!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 JustUs, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->



</html>

app/views/pages/about.html.erb
<body>


    <!-- Page Content -->
    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">About Us
                    <small>It's Nice to Meet You!</small>
                </h1>
                <p>Walls-Social Injustice is a website that deals with various forms of social injustice. This is a site that is meant to support people are suffering from today due to social injustices such as racism, feminism, and more. The site’s mission is to make sure people with the same social injustice  interests (can filtered based on community, state, or even country) can express concerns without the fear of being insulted or derogated-the wall can only be opened to the public with user permission. This website is also meant to provide resources for the benefit of anyone, not just those suffering from social injustice:  links, primary sources, videos, and even public opinion on the social injustice the user is focused on. The user, when signing up, chooses without binding a social injustice they want to focus on, makes a wall page/forum that allows the user to get other people’s opinions on the topic, get a page of general resources, and  a communities page that has resources about organizations and events in user’s state.
This a safe website where we encourage people to share their fears, questions, and anything else that would give them comfort. We hope that people from all over the world can use this site to comfort them and reassure them in this harsh world.  
</p>
<h2>Our Highlights</h2>
<p2>People can use our site to find resources on different organizations that they can find in their state or nearby. There are also current events that can help users be updated on what is going on with the social injustice they are researching or are interested in because they are negatively impacted by it. People can do this with leisure and do not have to go through google to find reliable sources. Also, the site will continue to change its news feeds so that they are as current as possible.
</p2>
</div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Alton Stovall
                    <small>Head Manager</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Charity Midenyo
                    <small>Head Programmer</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Wonhee Han
                    <small>Content Manager</small>
                </h3>
                <img src="http://projectgreenschools.org/wp/wp-content/uploads/2016/01/andoverhighschoolWonhee.png"/>
                <p>He is an aspiring student from Andover, MA, and he has worked very passionately for this mission. He has been responsible for all the research and the resources that were critical to the making of the project. He has been active in the HTML and CSS part of this website.</p></p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Alejandra Salazar
                    <small>Designer</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Natalie Melo
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Anthony Vigil
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
        </div>

        <hr>

    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/pages/home.html.erb
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="http://blog.hihostels.com/wp-content/uploads/2013/11/A-global-community-of-travellers1.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><strong>A community for everyone.</strong></h1>
              <p style="color:black">Experience community in a way you never have before. Interact and meet with people who identify and share similiar struggles with you. Join a safe space where people are free to contribute their own personal stories without the pressures of traditional social media.</p>
<<<<<<< HEAD
              <p><%= link_to "Sign up today", new_user_registration_path, class: "btn btn-lg btn-primary", role: "button" %></p>
=======
              <p><a class="btn btn-lg btn-primary" href="/users/sign_up" role="button">Sign up today</a></p>
>>>>>>> walltemplate
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="https://theverbatim.files.wordpress.com/2015/07/5847851379_ab2d87015f_o.jpg?w=1920&h=768&crop=1" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Be Reassured</h1>
              <p>Our site wants to remind the nation that those who are suffering from social injustice in any form are not bein forgotten. We would like to reach out and give a helping hand!</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="http://polishedcreatives.com/wp-content/uploads/2015/07/BlackLivesMatter-1.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><strong>Get involved.</strong></h1>
<<<<<<< HEAD
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="/pages/resources" role="button">Browse related organizations</a></p>
=======
              <p> Go to the forums and discuss information and opinions on social injustice. One can also go to the resources page for news feeds, primary sources, links to organizations that deal with social injustice, and more!</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse partner organizations</a></p>
>>>>>>> resources
            </div>
          </div>
        </div>s
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="https://cdn1.iconfinder.com/data/icons/mixed-long-shadow/512/brick_wall-128.png" alt="Generic placeholder image" width="140" height="140">
          <h2>My Wall</h2>
          <p>Your own personally designed page where you can post your individual feelings about social injustice and is viewed only by those who have the same interest. </p>
          <p><a class="btn btn-default" href="/pages/samplewall" role="button">Click Here &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="https://cdn.sencha.com/img/20120920-forum-icon.png" alt="Generic placeholder image" width="140" height="140">
          <h2>Forums</h2>
          <p>A place where people of diverse backgrounds can come together and have important dicussions in the world of social injustice.</p>
          <p><a class="btn btn-default" href="#" role="button">Click Here &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="http://www.staffmap.com/images/icons/support/forums.png" alt="Generic placeholder image" width="140" height="140">
          <h2>Support</h2>
<<<<<<< HEAD
          <p>Want even more personalized support? dlwnfowihghriooreignlfk</p>
          <p><a class="btn btn-default" href="/pages/resources" role="button">Click Here &raquo;</a></p>
=======
          <p>Want even more personalized support? Click on this page</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
>>>>>>> resources
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Express, Express! Equality!! <span class="text-muted">What to do?</span></h2>
          <p class="lead">This website is a great website that involves freedom of expression in which one can express feelings and interests about a certain field of social injustice
   outlined below. One can also get resources such as prmiary sources, links and connections to nearby or statewide organizationsconnect to your topic. The topic is shown in the table. You do not have to pick the topic for your resources, but for the wall, or forum, you make 
   you will have to get a set topic.</p>
        </div>
        <div class="col-md-5">
          
          <img src="http://www.kars4kids.org/blog/wp-content/uploads/2014/11/social-injustice.jpg"/>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Why join, Do You Ask?  <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">This is a website that provides not only ways to express feelings about social injustice with those interested in such areas, but also allows users access to reliable information and continuously chaning news feeds on current events. The user is provided with information on what kind of social injustice is happening in the country, the user's state, and what the country is doing about it. 
          that provide information on what is happeninig in the U.S. on social injustice. The forum is meant for all users to be able to freely express(the wall is more restricted to public view but all contributors to the forum are protected) feelings and ideas about such tragic or infuriating events that relate to the social injustice topic they have chosen when they signed up. It is useful for anyone, students, teachers, and anyone who are negatively affected by such injustices.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
           <img src="http://3.bp.blogspot.com/_1J306vb41nc/S0EDX_do0RI/AAAAAAAAADI/viZfKei7gJg/s320/human_rights_first.jpg"/>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Protection, Freedom, Safety! <span class="text-muted">Take a Look!</span></h2>
          <p class="lead">The website guarantees that your freedom of expression will not be hindered(unless they are corrosive or derogative). The site also protects what you write from any public viewer unless he/she is part of the same focus as you in terms of walls. It is also important to know that you can prevent anyone from commenting on your wall!!!!
</p>
        </div>
        <div class="col-md-5">
         
           <img src="http://injusticestories.com/wp-content/uploads/2015/01/2.jpg"/>
        </div>
      </div>

      <hr class="featurette-divider">
    </div>

      <!-- /END THE FEATURETTES -->


      

app/views/pages/samplewall.html.erb
    <link type="text/css" rel="stylesheet" href="wall.css"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<body background="http://www.easyfreepatterns.com/patterns/0/free-gray-and-white-mini-grid-seamless-tileable-background-pattern--929.gif">

    <div class="brand">WELCOME TO YOUR WALL</div>
    <div class="address-bar"></div>

    
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <a href="http://www.nytimes.com/video/us/100000004528049/alton-sterlings-son-calls-for-unity.html">
                                <img class="img-responsive img-full" src="http://a.abcnews.com/images/US/GTY_dallas_police_shootings_protest_2_jt_160710_12x5_1600.jpg" alt=""></a>
                            </div>
                            <div class="item">
                                <a href="http://www.huffingtonpost.com/entry/black-lives-matter-rio-brazil-olympics_us_5786f996e4b08608d332f81f">
                                <img class="img-responsive img-full" src="http://img.huffingtonpost.com/asset/scalefit_970_noupscale/57870a1b1a00002700dd1455.jpeg" alt=""></a>
                            </div>
                            <div class="item">
                                <a href="http://www.washingtonpost.com/news/arts-and-entertainment/wp/2016/07/13/the-most-powerful-art-from-the-blacklivesmatter-movement-three-years-in/">
                                <img class="img-responsive img-full" src="http://www.theaesthete.com/wp-content/uploads/2015/02/black-lives-matter-hero-1440x738.jpg" alt=""></a>
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"><i class="material-icons">forum</i></i> Forums</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Click Here</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"><i class="material-icons">view_headline</i></i> News</h4>
                    </div>
                    <div class="panel-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"><i class="material-icons">language</i></i> Social Media</h4>
                    </div>
                    <div class="panel-body">
                        <a class="twitter-timeline" href="https://twitter.com/Blklivesmatter">Tweets by Blklivesmatter</a>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                    </div>
                </div>
            </div>
        </div>

app/views/thredded/posts/_post.html.erb
<% cache(post, expires_in: 1.week) do %>
  <%= content_tag :article, id: dom_id(post), class: 'thredded--post' do %>
    <%= render 'thredded/posts_common/header', post: post %>
    <%= render 'thredded/posts_common/content', post: post %>
    <%= render 'thredded/posts_common/actions', post: post %>
    <p> hi friend</p>
    <% if post.pending_moderation? && !Thredded.content_visible_while_pending_moderation %>
      <p class="thredded--alert thredded--alert-warning"><%= t 'thredded.posts.pending_moderation_notice' %></p>
    <% elsif post.blocked? && post.can_moderate? %>
      <p class="thredded--alert thredded--alert-danger">
        <%= render 'thredded/shared/content_moderation_blocked_state', moderation_record: post.last_moderation_record %>
      </p>
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/walls/_join.html.erb
<%= form_for(current_user.wall_memberships.build) do |f| %>
    <div><%= hidden_field_tag :wall_id, wall.id %></div>
    <%= f.submit "Join", class: "btn btn-primary" %>
<% end %>

app/views/walls/edit.html.erb
<h1>Editing Wall</h1>

<%= render 'form' %>

<%= link_to 'Show', @wall %> |
<%= link_to 'Back', walls_path %>

app/views/walls/index.html.erb
<p id="notice"><%= notice %></p>

<% if @user_walls.count==0 %>
  congratulations on creating a walls profile! Please select the wall(s) you would like to join.
  
  <% @walls.each do |wall| %>
    <%= wall.title %>
    <%= render "join_form", wall: wall if user_signed_in? %>
  <% end %>


<% else %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @walls.each do |wall| %>
        <tr>
          <td><%= wall.title %></td>
          <td><%= wall.description %></td>
              <%= render "join_form", wall: wall if user_signed_in? %>

          <td><%= link_to 'Show', wall %></td>
          <td><%= link_to 'Edit', edit_wall_path(wall) %></td>
          <td><%= link_to 'Destroy', wall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>


<br>

<%= link_to 'New Wall', new_wall_path %>

app/views/walls/new.html.erb
<h1>New Wall</h1>

<%= render 'form' %>

<%= link_to 'Back', walls_path %>

app/views/walls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wall.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wall.description %>
</p>

 <%= render "join_form", wall: @wall if user_signed_in? %>

<%= link_to 'Edit', edit_wall_path(@wall) %> |
<%= link_to 'Back', walls_path %> |
<%= link_to 'forum',@forum %>